<?php
/** @var \Space48\CustomerReviews\Block\Success $block */
?>

<?php if ($block->hasLastOrder()) : ?>
    <?php $order = $block->getLastOrder() ?>
    <div id="gts-order" style="display: none" translate="no">
        <span id="gts-o-id"><?php echo $order->getIncrementId(); ?></span>
        <span id="gts-o-domain"><?php echo $block->getFormattedBaseUrl(); ?></span>
        <span id="gts-o-email"><?php echo $order->getCustomerEmail(); ?></span>
        <span id="gts-o-country"><?php echo $block->getOrderCountry(); ?></span>
        <span id="gts-o-currency"><?php echo $order->getBaseCurrencyCode(); ?></span>
        <span id="gts-o-total"><?php echo $block->formatPrice($order->getBaseGrandTotal()); ?></span>
        <span id="gts-o-discounts"><?php echo $block->formatPrice($order->getBaseDiscountAmount()); ?></span>
        <span id="gts-o-shipping-total"><?php echo $block->formatPrice($order->getBaseShippingAmount()); ?></span>
        <span id="gts-o-tax-total"><?php echo $block->formatPrice($order->getBaseTaxAmount()); ?></span>
        <span id="gts-o-est-ship-date"><?php echo $block->getEstimatedShippingDate(); ?></span>
        <span id="gts-o-est-delivery-date"><?php echo $block->getEstimatedDeliveryDate() ?></span>
        <span id="gts-o-has-preorder"><?php echo $block->getOrderHasPreOrders() ?></span>
        <span id="gts-o-has-digital"><?php echo $block->isVirtual() ?></span>
        <?php $i = 1 ?>
        <?php /** @var \Magento\Sales\Model\Order\Item $_item */ ?>
        <?php foreach ($block->getAllVisibleItems() as $_item) : ?>
            <!-- start item <?php echo $i; ?> -->
            <span class="gts-item">
                <span class="gts-i-name"><?php echo $_item->getName() ?></span>
                <span class="gts-i-price"><?php echo $block->formatPrice($_item->getBaseOriginalPrice()) ?></span>
                <span class="gts-i-quantity"><?php echo round($_item->getQtyOrdered()) ?></span>
                <span class="gts-i-prodsearch-id"><?php echo $_item->getSku(); ?></span>
                <span class="gts-i-prodsearch-store-id"><?php echo $block->getGoogleShoppingAccountId() ?></span>
            </span>
            <!-- end item <?php echo $i; ?> -->
            <?php $i ++ ?>
        <?php endforeach ?>
    </div>
<?php endif ?>

